# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WinLinkMon_GUI_12_12_19.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pylogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setGeometry(QtCore.QRect(0, 10, 990, 700))
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.recv_tabWidget = QtWidgets.QTabWidget(self.frameMain)
        self.recv_tabWidget.setGeometry(QtCore.QRect(20, 10, 965, 420))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        self.recv_tabWidget.setFont(font)
        self.recv_tabWidget.setObjectName("recv_tabWidget")
        self.tab_pmon_capture = QtWidgets.QWidget()
        self.tab_pmon_capture.setObjectName("tab_pmon_capture")
        self.recv_pmoncap = QtWidgets.QTextEdit(self.tab_pmon_capture)
        self.recv_pmoncap.setGeometry(QtCore.QRect(10, 30, 935, 350))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recv_pmoncap.setFont(font)
        self.recv_pmoncap.setObjectName("recv_pmoncap")
        self.label_recvpmon = QtWidgets.QLabel(self.tab_pmon_capture)
        self.label_recvpmon.setGeometry(QtCore.QRect(170, 0, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_recvpmon.setFont(font)
        self.label_recvpmon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recvpmon.setObjectName("label_recvpmon")
        self.capfileLineEdit = QtWidgets.QLineEdit(self.tab_pmon_capture)
        self.capfileLineEdit.setGeometry(QtCore.QRect(420, 0, 401, 29))
        self.capfileLineEdit.setObjectName("capfileLineEdit")
        self.recv_tabWidget.addTab(self.tab_pmon_capture, "")
        self.tab_comp_payload2 = QtWidgets.QWidget()
        self.tab_comp_payload2.setObjectName("tab_comp_payload2")
        self.recv_payload2 = QtWidgets.QTextEdit(self.tab_comp_payload2)
        self.recv_payload2.setGeometry(QtCore.QRect(10, 30, 935, 390))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recv_payload2.setFont(font)
        self.recv_payload2.setObjectName("recv_payload2")
        self.label_recvpayload2 = QtWidgets.QLabel(self.tab_comp_payload2)
        self.label_recvpayload2.setGeometry(QtCore.QRect(240, 0, 321, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_recvpayload2.setFont(font)
        self.label_recvpayload2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recvpayload2.setObjectName("label_recvpayload2")
        self.payload2LineEdit = QtWidgets.QLineEdit(self.tab_comp_payload2)
        self.payload2LineEdit.setGeometry(QtCore.QRect(790, 0, 151, 29))
        self.payload2LineEdit.setObjectName("payload2LineEdit")
        self.label_pmon_binlen = QtWidgets.QLabel(self.tab_comp_payload2)
        self.label_pmon_binlen.setGeometry(QtCore.QRect(660, 0, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_pmon_binlen.setFont(font)
        self.label_pmon_binlen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pmon_binlen.setObjectName("label_pmon_binlen")
        self.recv_tabWidget.addTab(self.tab_comp_payload2, "")
        self.tab_decomp_msg = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tab_decomp_msg.setFont(font)
        self.tab_decomp_msg.setObjectName("tab_decomp_msg")
        self.recv_decompmsg = QtWidgets.QTextEdit(self.tab_decomp_msg)
        self.recv_decompmsg.setGeometry(QtCore.QRect(10, 30, 935, 390))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recv_decompmsg.setFont(font)
        self.recv_decompmsg.setObjectName("recv_decompmsg")
        self.label_decompmsg = QtWidgets.QLabel(self.tab_decomp_msg)
        self.label_decompmsg.setGeometry(QtCore.QRect(10, 0, 931, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_decompmsg.setFont(font)
        self.label_decompmsg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_decompmsg.setObjectName("label_decompmsg")
        self.recv_tabWidget.addTab(self.tab_decomp_msg, "")
        self.tab_hexdump = QtWidgets.QWidget()
        self.tab_hexdump.setObjectName("tab_hexdump")
        self.label_hexdump = QtWidgets.QLabel(self.tab_hexdump)
        self.label_hexdump.setGeometry(QtCore.QRect(10, 0, 931, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hexdump.setFont(font)
        self.label_hexdump.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hexdump.setObjectName("label_hexdump")
        self.recv_hexdump = QtWidgets.QTextEdit(self.tab_hexdump)
        self.recv_hexdump.setGeometry(QtCore.QRect(10, 30, 935, 390))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recv_hexdump.setFont(font)
        self.recv_hexdump.setObjectName("recv_hexdump")
        self.recv_tabWidget.addTab(self.tab_hexdump, "")
        self.chk_verbose = QtWidgets.QCheckBox(self.frameMain)
        self.chk_verbose.setGeometry(QtCore.QRect(20, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_verbose.setFont(font)
        self.chk_verbose.setObjectName("chk_verbose")
        self.chk_padinsert = QtWidgets.QCheckBox(self.frameMain)
        self.chk_padinsert.setGeometry(QtCore.QRect(380, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_padinsert.setFont(font)
        self.chk_padinsert.setObjectName("chk_padinsert")
        self.chk_strip025B = QtWidgets.QCheckBox(self.frameMain)
        self.chk_strip025B.setGeometry(QtCore.QRect(500, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_strip025B.setFont(font)
        self.chk_strip025B.setObjectName("chk_strip025B")
        self.chk_strip16 = QtWidgets.QCheckBox(self.frameMain)
        self.chk_strip16.setGeometry(QtCore.QRect(620, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_strip16.setFont(font)
        self.chk_strip16.setObjectName("chk_strip16")
        self.chk_stripeof = QtWidgets.QCheckBox(self.frameMain)
        self.chk_stripeof.setGeometry(QtCore.QRect(750, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_stripeof.setFont(font)
        self.chk_stripeof.setObjectName("chk_stripeof")
        self.chk_openbin = QtWidgets.QCheckBox(self.frameMain)
        self.chk_openbin.setGeometry(QtCore.QRect(140, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_openbin.setFont(font)
        self.chk_openbin.setObjectName("chk_openbin")
        self.chk_binmatch = QtWidgets.QCheckBox(self.frameMain)
        self.chk_binmatch.setEnabled(False)
        self.chk_binmatch.setGeometry(QtCore.QRect(260, 440, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_binmatch.setFont(font)
        self.chk_binmatch.setChecked(True)
        self.chk_binmatch.setObjectName("chk_binmatch")
        self.chk_runpopen = QtWidgets.QCheckBox(self.frameMain)
        self.chk_runpopen.setGeometry(QtCore.QRect(860, 440, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.chk_runpopen.setFont(font)
        self.chk_runpopen.setChecked(True)
        self.chk_runpopen.setObjectName("chk_runpopen")
        self.logFrame = QtWidgets.QFrame(self.frameMain)
        self.logFrame.setGeometry(QtCore.QRect(10, 480, 960, 140))
        self.logFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logFrame.setObjectName("logFrame")
        self.logTextEdit = QtWidgets.QTextEdit(self.logFrame)
        self.logTextEdit.setGeometry(QtCore.QRect(0, 0, 960, 140))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.logTextEdit.setFont(font)
        self.logTextEdit.setObjectName("logTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuEdit.setFont(font)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuView.setFont(font)
        self.menuView.setObjectName("menuView")
        self.menuAssembly = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuAssembly.setFont(font)
        self.menuAssembly.setObjectName("menuAssembly")
        self.menuConversion = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menuConversion.setFont(font)
        self.menuConversion.setObjectName("menuConversion")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.newFile = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Files-New-File-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newFile.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.newFile.setFont(font)
        self.newFile.setObjectName("newFile")
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Folder-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFile.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.openFile.setFont(font)
        self.openFile.setObjectName("openFile")
        self.saveFile = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Actions-document-save-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveFile.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.saveFile.setFont(font)
        self.saveFile.setObjectName("saveFile")
        self.saveFile_As = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.saveFile_As.setFont(font)
        self.saveFile_As.setObjectName("saveFile_As")
        self.printLog = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Printer-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printLog.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.printLog.setFont(font)
        self.printLog.setObjectName("printLog")
        self.actionReset = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionReset.setFont(font)
        self.actionReset.setObjectName("actionReset")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Button-Close-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionQuit.setFont(font)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionUndo.setFont(font)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionRedo.setFont(font)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Editing-Cut-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionCut.setFont(font)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Copy-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionCopy.setFont(font)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Paste-icon24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon8)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.actionPaste.setFont(font)
        self.actionPaste.setObjectName("actionPaste")
        self.sendText_hexDump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendText_hexDump.setFont(font)
        self.sendText_hexDump.setObjectName("sendText_hexDump")
        self.sendUncBin_hexDump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendUncBin_hexDump.setFont(font)
        self.sendUncBin_hexDump.setObjectName("sendUncBin_hexDump")
        self.sendCompBin_hexDump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendCompBin_hexDump.setFont(font)
        self.sendCompBin_hexDump.setObjectName("sendCompBin_hexDump")
        self.recvCapture_HexDump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recvCapture_HexDump.setFont(font)
        self.recvCapture_HexDump.setObjectName("recvCapture_HexDump")
        self.recvPayload2_HexDump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recvPayload2_HexDump.setFont(font)
        self.recvPayload2_HexDump.setObjectName("recvPayload2_HexDump")
        self.recvDecomp_HexDump = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recvDecomp_HexDump.setFont(font)
        self.recvDecomp_HexDump.setObjectName("recvDecomp_HexDump")
        self.assySendTextFiles = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.assySendTextFiles.setFont(font)
        self.assySendTextFiles.setObjectName("assySendTextFiles")
        self.assyCapture = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.assyCapture.setFont(font)
        self.assyCapture.setObjectName("assyCapture")
        self.sendText_to_sendUncBin = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendText_to_sendUncBin.setFont(font)
        self.sendText_to_sendUncBin.setObjectName("sendText_to_sendUncBin")
        self.sendText_to_sendCompBin = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendText_to_sendCompBin.setFont(font)
        self.sendText_to_sendCompBin.setObjectName("sendText_to_sendCompBin")
        self.sendCompBin_to_recvCompBin = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sendCompBin_to_recvCompBin.setFont(font)
        self.sendCompBin_to_recvCompBin.setObjectName("sendCompBin_to_recvCompBin")
        self.recvPmon_to_Payload2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recvPmon_to_Payload2.setFont(font)
        self.recvPmon_to_Payload2.setObjectName("recvPmon_to_Payload2")
        self.recvPayload2_to_DecompMsg = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recvPayload2_to_DecompMsg.setFont(font)
        self.recvPayload2_to_DecompMsg.setObjectName("recvPayload2_to_DecompMsg")
        self.assyPayload2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.assyPayload2.setFont(font)
        self.assyPayload2.setObjectName("assyPayload2")
        self.recvPmon_to_DecompMsg = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.recvPmon_to_DecompMsg.setFont(font)
        self.recvPmon_to_DecompMsg.setObjectName("recvPmon_to_DecompMsg")
        self.about_WinLinkMon = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.about_WinLinkMon.setFont(font)
        self.about_WinLinkMon.setObjectName("about_WinLinkMon")
        self.documentation = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.documentation.setFont(font)
        self.documentation.setObjectName("documentation")
        self.printText = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.printText.setFont(font)
        self.printText.setObjectName("printText")
        self.menuFile.addAction(self.newFile)
        self.menuFile.addAction(self.openFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.saveFile)
        self.menuFile.addAction(self.saveFile_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.printLog)
        self.menuFile.addAction(self.printText)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuView.addAction(self.recvCapture_HexDump)
        self.menuView.addAction(self.recvPayload2_HexDump)
        self.menuView.addAction(self.recvDecomp_HexDump)
        self.menuAssembly.addAction(self.assyCapture)
        self.menuAssembly.addAction(self.assyPayload2)
        self.menuConversion.addAction(self.recvPmon_to_Payload2)
        self.menuConversion.addAction(self.recvPayload2_to_DecompMsg)
        self.menuConversion.addSeparator()
        self.menuConversion.addAction(self.recvPmon_to_DecompMsg)
        self.menuHelp.addAction(self.about_WinLinkMon)
        self.menuHelp.addAction(self.documentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAssembly.menuAction())
        self.menubar.addAction(self.menuConversion.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.newFile)
        self.toolBar.addAction(self.openFile)
        self.toolBar.addAction(self.saveFile)
        self.toolBar.addAction(self.printLog)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)

        self.retranslateUi(MainWindow)
        self.recv_tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionRedo.triggered.connect(self.recv_payload2.redo)
        self.actionUndo.triggered.connect(self.recv_payload2.undo)
        self.actionRedo.triggered.connect(self.recv_hexdump.redo)
        self.actionRedo.triggered.connect(self.recv_pmoncap.redo)
        self.actionRedo.triggered.connect(self.recv_decompmsg.redo)
        self.actionUndo.triggered.connect(self.recv_decompmsg.undo)
        self.actionUndo.triggered.connect(self.recv_hexdump.undo)
        self.actionUndo.triggered.connect(self.recv_pmoncap.undo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.recv_tabWidget, self.recv_pmoncap)
        MainWindow.setTabOrder(self.recv_pmoncap, self.recv_payload2)
        MainWindow.setTabOrder(self.recv_payload2, self.recv_decompmsg)
        MainWindow.setTabOrder(self.recv_decompmsg, self.recv_hexdump)
        MainWindow.setTabOrder(self.recv_hexdump, self.chk_verbose)
        MainWindow.setTabOrder(self.chk_verbose, self.chk_openbin)
        MainWindow.setTabOrder(self.chk_openbin, self.chk_binmatch)
        MainWindow.setTabOrder(self.chk_binmatch, self.chk_padinsert)
        MainWindow.setTabOrder(self.chk_padinsert, self.chk_strip025B)
        MainWindow.setTabOrder(self.chk_strip025B, self.chk_strip16)
        MainWindow.setTabOrder(self.chk_strip16, self.chk_stripeof)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WinLink Message Monitor"))
        self.label_recvpmon.setText(_translate("MainWindow", "Received PMON Capture File"))
        self.recv_tabWidget.setTabText(self.recv_tabWidget.indexOf(self.tab_pmon_capture), _translate("MainWindow", "PMON Capture"))
        self.label_recvpayload2.setText(_translate("MainWindow", "Received Compressed Binary PAYLOAD2"))
        self.label_pmon_binlen.setText(_translate("MainWindow", "pmon_binlen:"))
        self.recv_tabWidget.setTabText(self.recv_tabWidget.indexOf(self.tab_comp_payload2), _translate("MainWindow", "Compressed PAYLOAD2"))
        self.label_decompmsg.setText(_translate("MainWindow", "Receive Decompressed WinLink Message"))
        self.recv_tabWidget.setTabText(self.recv_tabWidget.indexOf(self.tab_decomp_msg), _translate("MainWindow", "Decompressed MSG"))
        self.label_hexdump.setText(_translate("MainWindow", "Received Hex Dump"))
        self.recv_tabWidget.setTabText(self.recv_tabWidget.indexOf(self.tab_hexdump), _translate("MainWindow", "Hex Dump"))
        self.chk_verbose.setText(_translate("MainWindow", "Verbose Log"))
        self.chk_padinsert.setText(_translate("MainWindow", "Pad Insert"))
        self.chk_strip025B.setText(_translate("MainWindow", "Strip 025B"))
        self.chk_strip16.setText(_translate("MainWindow", "Strip16 Bytes"))
        self.chk_stripeof.setText(_translate("MainWindow", "Strip EOF"))
        self.chk_openbin.setText(_translate("MainWindow", "Open Binary"))
        self.chk_binmatch.setText(_translate("MainWindow", "BinMatch"))
        self.chk_runpopen.setText(_translate("MainWindow", "Run / POpen"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "Hex Dump"))
        self.menuAssembly.setTitle(_translate("MainWindow", "Assembly"))
        self.menuConversion.setTitle(_translate("MainWindow", "Conversion"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.newFile.setText(_translate("MainWindow", "&New"))
        self.newFile.setStatusTip(_translate("MainWindow", "File New"))
        self.newFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.openFile.setText(_translate("MainWindow", "&Open"))
        self.openFile.setStatusTip(_translate("MainWindow", "File Open"))
        self.openFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.saveFile.setText(_translate("MainWindow", "&Save"))
        self.saveFile.setStatusTip(_translate("MainWindow", "File Save"))
        self.saveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.saveFile_As.setText(_translate("MainWindow", "Save As"))
        self.saveFile_As.setStatusTip(_translate("MainWindow", "File Save As"))
        self.printLog.setText(_translate("MainWindow", "&Print Log "))
        self.printLog.setStatusTip(_translate("MainWindow", "Print Log"))
        self.printLog.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionReset.setText(_translate("MainWindow", "&Reset and Clear"))
        self.actionReset.setStatusTip(_translate("MainWindow", "File Close"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit/Exit Program"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionUndo.setStatusTip(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionRedo.setText(_translate("MainWindow", "&Redo"))
        self.actionRedo.setStatusTip(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionCut.setText(_translate("MainWindow", "&Cut"))
        self.actionCut.setStatusTip(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "&Copy"))
        self.actionCopy.setStatusTip(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "&Paste"))
        self.actionPaste.setStatusTip(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.sendText_hexDump.setText(_translate("MainWindow", "Send Text File"))
        self.sendUncBin_hexDump.setText(_translate("MainWindow", "Send Binary File"))
        self.sendCompBin_hexDump.setText(_translate("MainWindow", "Send Compressed File"))
        self.recvCapture_HexDump.setText(_translate("MainWindow", "PMON Capture File"))
        self.recvPayload2_HexDump.setText(_translate("MainWindow", "Compressed PAYLOAD2"))
        self.recvDecomp_HexDump.setText(_translate("MainWindow", "Decompressed Message"))
        self.assySendTextFiles.setText(_translate("MainWindow", "Send Text File(s)"))
        self.assyCapture.setText(_translate("MainWindow", "PMON Capture Files"))
        self.sendText_to_sendUncBin.setText(_translate("MainWindow", "Send Text to Send UncompBin"))
        self.sendText_to_sendCompBin.setText(_translate("MainWindow", "Send Text to Send CompBin"))
        self.sendCompBin_to_recvCompBin.setText(_translate("MainWindow", "Send CompBin to Send Recv CompBin"))
        self.recvPmon_to_Payload2.setText(_translate("MainWindow", "Recv PMON Capture to Compressed PAYLOAD2"))
        self.recvPayload2_to_DecompMsg.setText(_translate("MainWindow", "Recv Compressed PAYLOAD2 to Decompressed MSG"))
        self.assyPayload2.setText(_translate("MainWindow", "Compressed PAYLOAD2\'s"))
        self.recvPmon_to_DecompMsg.setText(_translate("MainWindow", "Recv PMON Capture to Decompressed MSG"))
        self.about_WinLinkMon.setText(_translate("MainWindow", "About WinLinkMon"))
        self.documentation.setText(_translate("MainWindow", "Documentation"))
        self.printText.setText(_translate("MainWindow", "Print Text Buffer"))
        self.printText.setStatusTip(_translate("MainWindow", "Print Textbox"))
        self.printText.setShortcut(_translate("MainWindow", "Ctrl+P"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

